name: Build and Publish to NuGet

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [ published ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
    
    - name: Restore dependencies
      run: dotnet restore DepFinder.sln
    
    - name: Build
      run: dotnet build DepFinder.sln --no-restore --configuration Release
    
    - name: Test
      run: dotnet test DepFinder.sln --no-build --configuration Release --verbosity normal
      continue-on-error: true
  
  publish:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
    
    - name: Generate version
      id: version
      run: |
        VERSION="1.0.${{ github.run_number }}"
        echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
        echo "Generated version: $VERSION"
    
    - name: Restore dependencies
      run: dotnet restore DepFinder.sln
    
    - name: Build
      run: dotnet build DepFinder.sln --no-restore --configuration Release
    
    - name: Pack
      run: dotnet pack DepFinder.Service/DepFinder.Service.csproj --no-build --configuration Release --output ./artifacts -p:PackageVersion=${{ steps.version.outputs.VERSION }}
    
    - name: Publish to NuGet
      run: dotnet nuget push ./artifacts/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate